name = "after-gruv"
description = "A robust, elegant dark theme"
license = "MIT"
homepage = "https://github.com/artis101/after-gruv"
min_version = "0.17.0"
demo = "https://artis101.github.io/after-gruv/"

[extra]


[author]
name = "Artis Avotins"
homepage = "https://www.artisavotins.com"

[original]
author =  "Vincent Prouillet"
homepage = "https://getzola.github.io/after-dark/"
repo = "https://github.com/getzola/after-dark"
